/**
 * BPMN Engine OpenAPI
 * REST API for lib-bpmn-engine
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BpmnEngineOpenApi);
  }
}(this, function(expect, BpmnEngineOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BpmnEngineOpenApi.Job();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Job', function() {
    it('should create an instance of Job', function() {
      // uncomment below and update the code to test Job
      //var instance = new BpmnEngineOpenApi.Job();
      //expect(instance).to.be.a(BpmnEngineOpenApi.Job);
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new BpmnEngineOpenApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property elementId (base name: "elementId")', function() {
      // uncomment below and update the code to test the property elementId
      //var instance = new BpmnEngineOpenApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property elementInstanceKey (base name: "elementInstanceKey")', function() {
      // uncomment below and update the code to test the property elementInstanceKey
      //var instance = new BpmnEngineOpenApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property processInstanceKey (base name: "processInstanceKey")', function() {
      // uncomment below and update the code to test the property processInstanceKey
      //var instance = new BpmnEngineOpenApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new BpmnEngineOpenApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new BpmnEngineOpenApi.Job();
      //expect(instance).to.be();
    });

  });

}));
