/**
 * BPMN Engine OpenAPI
 * REST API for lib-bpmn-engine
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BpmnEngineOpenApi);
  }
}(this, function(expect, BpmnEngineOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BpmnEngineOpenApi.ProcessDefinitionDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProcessDefinitionDetail', function() {
    it('should create an instance of ProcessDefinitionDetail', function() {
      // uncomment below and update the code to test ProcessDefinitionDetail
      //var instance = new BpmnEngineOpenApi.ProcessDefinitionDetail();
      //expect(instance).to.be.a(BpmnEngineOpenApi.ProcessDefinitionDetail);
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new BpmnEngineOpenApi.ProcessDefinitionDetail();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new BpmnEngineOpenApi.ProcessDefinitionDetail();
      //expect(instance).to.be();
    });

    it('should have the property bpmnProcessId (base name: "bpmnProcessId")', function() {
      // uncomment below and update the code to test the property bpmnProcessId
      //var instance = new BpmnEngineOpenApi.ProcessDefinitionDetail();
      //expect(instance).to.be();
    });

    it('should have the property bpmnData (base name: "bpmnData")', function() {
      // uncomment below and update the code to test the property bpmnData
      //var instance = new BpmnEngineOpenApi.ProcessDefinitionDetail();
      //expect(instance).to.be();
    });

  });

}));
