/* tslint:disable */
/* eslint-disable */
/**
 * ZenBPM OpenAPI
 * REST API for ZenBPM
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: info@pbinitiative.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

