/**
 * BPMN Engine OpenAPI
 * REST API for lib-bpmn-engine
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CompleteJobRequest from '../model/CompleteJobRequest';

/**
* Jobs service.
* @module api/JobsApi
* @version 0.1.0
*/
export default class JobsApi {

    /**
    * Constructs a new JobsApi. 
    * @alias module:api/JobsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the completeJob operation.
     * @callback module:api/JobsApi~completeJobCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Complete a job
     * @param {module:model/CompleteJobRequest} completeJobRequest 
     * @param {module:api/JobsApi~completeJobCallback} callback The callback function, accepting three arguments: error, data, response
     */
    completeJob(completeJobRequest, callback) {
      let postBody = completeJobRequest;
      // verify the required parameter 'completeJobRequest' is set
      if (completeJobRequest === undefined || completeJobRequest === null) {
        throw new Error("Missing the required parameter 'completeJobRequest' when calling completeJob");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/jobs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
