/**
 * BPMN Engine OpenAPI
 * REST API for lib-bpmn-engine
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Activity from './Activity';
import PageMetadata from './PageMetadata';

/**
 * The ActivityPage model module.
 * @module model/ActivityPage
 * @version 0.1.0
 */
class ActivityPage {
    /**
     * Constructs a new <code>ActivityPage</code>.
     * @alias module:model/ActivityPage
     * @implements module:model/PageMetadata
     */
    constructor() { 
        PageMetadata.initialize(this);
        ActivityPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActivityPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActivityPage} obj Optional instance to populate.
     * @return {module:model/ActivityPage} The populated <code>ActivityPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActivityPage();
            PageMetadata.constructFromObject(data, obj);

            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Activity]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ActivityPage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ActivityPage</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                Activity.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} offset
 */
ActivityPage.prototype['offset'] = undefined;

/**
 * @member {Number} size
 */
ActivityPage.prototype['size'] = undefined;

/**
 * @member {Number} count
 */
ActivityPage.prototype['count'] = undefined;

/**
 * @member {Array.<module:model/Activity>} items
 */
ActivityPage.prototype['items'] = undefined;


// Implement PageMetadata interface:
/**
 * @member {Number} offset
 */
PageMetadata.prototype['offset'] = undefined;
/**
 * @member {Number} size
 */
PageMetadata.prototype['size'] = undefined;
/**
 * @member {Number} count
 */
PageMetadata.prototype['count'] = undefined;




export default ActivityPage;

