/**
 * BPMN Engine OpenAPI
 * REST API for lib-bpmn-engine
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompleteJobRequest model module.
 * @module model/CompleteJobRequest
 * @version 0.1.0
 */
class CompleteJobRequest {
    /**
     * Constructs a new <code>CompleteJobRequest</code>.
     * @alias module:model/CompleteJobRequest
     * @param jobKey {Number} 
     */
    constructor(jobKey) { 
        
        CompleteJobRequest.initialize(this, jobKey);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jobKey) { 
        obj['jobKey'] = jobKey;
    }

    /**
     * Constructs a <code>CompleteJobRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompleteJobRequest} obj Optional instance to populate.
     * @return {module:model/CompleteJobRequest} The populated <code>CompleteJobRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompleteJobRequest();

            if (data.hasOwnProperty('jobKey')) {
                obj['jobKey'] = ApiClient.convertToType(data['jobKey'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompleteJobRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompleteJobRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CompleteJobRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

CompleteJobRequest.RequiredProperties = ["jobKey"];

/**
 * @member {Number} jobKey
 */
CompleteJobRequest.prototype['jobKey'] = undefined;






export default CompleteJobRequest;

