/**
 * BPMN Engine OpenAPI
 * REST API for lib-bpmn-engine
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateProcessInstanceRequest model module.
 * @module model/CreateProcessInstanceRequest
 * @version 0.1.0
 */
class CreateProcessInstanceRequest {
    /**
     * Constructs a new <code>CreateProcessInstanceRequest</code>.
     * @alias module:model/CreateProcessInstanceRequest
     * @param processDefinitionKey {String} 
     */
    constructor(processDefinitionKey) { 
        
        CreateProcessInstanceRequest.initialize(this, processDefinitionKey);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, processDefinitionKey) { 
        obj['processDefinitionKey'] = processDefinitionKey;
    }

    /**
     * Constructs a <code>CreateProcessInstanceRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateProcessInstanceRequest} obj Optional instance to populate.
     * @return {module:model/CreateProcessInstanceRequest} The populated <code>CreateProcessInstanceRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProcessInstanceRequest();

            if (data.hasOwnProperty('processDefinitionKey')) {
                obj['processDefinitionKey'] = ApiClient.convertToType(data['processDefinitionKey'], 'String');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateProcessInstanceRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateProcessInstanceRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateProcessInstanceRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['processDefinitionKey'] && !(typeof data['processDefinitionKey'] === 'string' || data['processDefinitionKey'] instanceof String)) {
            throw new Error("Expected the field `processDefinitionKey` to be a primitive type in the JSON string but got " + data['processDefinitionKey']);
        }

        return true;
    }


}

CreateProcessInstanceRequest.RequiredProperties = ["processDefinitionKey"];

/**
 * @member {String} processDefinitionKey
 */
CreateProcessInstanceRequest.prototype['processDefinitionKey'] = undefined;

/**
 * @member {Object} variables
 */
CreateProcessInstanceRequest.prototype['variables'] = undefined;






export default CreateProcessInstanceRequest;

