/**
 * BPMN Engine OpenAPI
 * REST API for lib-bpmn-engine
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActivityPage from './ActivityPage';

/**
 * The GetActivities200Response model module.
 * @module model/GetActivities200Response
 * @version 0.1.0
 */
class GetActivities200Response {
    /**
     * Constructs a new <code>GetActivities200Response</code>.
     * @alias module:model/GetActivities200Response
     */
    constructor() { 
        
        GetActivities200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetActivities200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetActivities200Response} obj Optional instance to populate.
     * @return {module:model/GetActivities200Response} The populated <code>GetActivities200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetActivities200Response();

            if (data.hasOwnProperty('activities')) {
                obj['activities'] = ApiClient.convertToType(data['activities'], [ActivityPage]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetActivities200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetActivities200Response</code>.
     */
    static validateJSON(data) {
        if (data['activities']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['activities'])) {
                throw new Error("Expected the field `activities` to be an array in the JSON data but got " + data['activities']);
            }
            // validate the optional field `activities` (array)
            for (const item of data['activities']) {
                ActivityPage.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ActivityPage>} activities
 */
GetActivities200Response.prototype['activities'] = undefined;






export default GetActivities200Response;

