/**
 * BPMN Engine OpenAPI
 * REST API for lib-bpmn-engine
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobPage from './JobPage';

/**
 * The GetJobs200Response model module.
 * @module model/GetJobs200Response
 * @version 0.1.0
 */
class GetJobs200Response {
    /**
     * Constructs a new <code>GetJobs200Response</code>.
     * @alias module:model/GetJobs200Response
     */
    constructor() { 
        
        GetJobs200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetJobs200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetJobs200Response} obj Optional instance to populate.
     * @return {module:model/GetJobs200Response} The populated <code>GetJobs200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetJobs200Response();

            if (data.hasOwnProperty('jobs')) {
                obj['jobs'] = ApiClient.convertToType(data['jobs'], [JobPage]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetJobs200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetJobs200Response</code>.
     */
    static validateJSON(data) {
        if (data['jobs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['jobs'])) {
                throw new Error("Expected the field `jobs` to be an array in the JSON data but got " + data['jobs']);
            }
            // validate the optional field `jobs` (array)
            for (const item of data['jobs']) {
                JobPage.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/JobPage>} jobs
 */
GetJobs200Response.prototype['jobs'] = undefined;






export default GetJobs200Response;

