/**
 * BPMN Engine OpenAPI
 * REST API for lib-bpmn-engine
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProcessInstancePage from './ProcessInstancePage';

/**
 * The GetProcessInstances200Response model module.
 * @module model/GetProcessInstances200Response
 * @version 0.1.0
 */
class GetProcessInstances200Response {
    /**
     * Constructs a new <code>GetProcessInstances200Response</code>.
     * @alias module:model/GetProcessInstances200Response
     */
    constructor() { 
        
        GetProcessInstances200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetProcessInstances200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProcessInstances200Response} obj Optional instance to populate.
     * @return {module:model/GetProcessInstances200Response} The populated <code>GetProcessInstances200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProcessInstances200Response();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('processInstances')) {
                obj['processInstances'] = ApiClient.convertToType(data['processInstances'], [ProcessInstancePage]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetProcessInstances200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetProcessInstances200Response</code>.
     */
    static validateJSON(data) {
        if (data['processInstances']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['processInstances'])) {
                throw new Error("Expected the field `processInstances` to be an array in the JSON data but got " + data['processInstances']);
            }
            // validate the optional field `processInstances` (array)
            for (const item of data['processInstances']) {
                ProcessInstancePage.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} total
 */
GetProcessInstances200Response.prototype['total'] = undefined;

/**
 * @member {Array.<module:model/ProcessInstancePage>} processInstances
 */
GetProcessInstances200Response.prototype['processInstances'] = undefined;






export default GetProcessInstances200Response;

